version: "3"
services:
  estoque-control-webapi:
    container_name: estoque-control-webapi
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - sqlserver
    ports:
      - 5000:80
      - 443:443
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Development#Env0319"
    volumes:
      - ./volumes/mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433

